name: store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Connectivity & Internet Check
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.2.0

  # Firebase
  firebase_core: ^3.4.1
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # State Management & Utils
  provider: ^6.1.1
  logger: ^2.5.0
  intl: ^0.19.0
  fluttertoast: ^8.2.10

  # Media & Payments
  image_picker: ^0.8.7+5
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/signupimg.png
    - assets/images/campuscart.png
    - assets/images/signinimg.png
